name: Build and Release

on:
  push:
    branches:
      - master
      - dev
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.build.outputs.version }}

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Run tests
        run: bun run test

      - name: Extract version from package.json
        id: version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create release
        uses: actions/publish-action@v0.3.0
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Release v${{ env.VERSION }}"
          body: "Release of version v${{ env.VERSION }}"
          draft: false
          prerelease: ${{ contains(github.ref, 'dev') }}
          files: "turtle-devtools-${{ env.VERSION }}.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}